_wandb:
    value:
        cli_version: 0.27.0
        e:
            8tg16heq1kwq21lcgjuuw75w7wlpy7zl:
                codePath: 3_evaluate_wb.py
                codePathLocal: 3_evaluate_wb.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "125829115904"
                        used: "18388660224"
                email: haider8237@gmail.com
                executable: E:\berlin-eventscout\venv\Scripts\python.exe
                host: DESKTOP-963FN0I
                memory:
                    total: "17052135424"
                os: Windows-10-10.0.26200-SP0
                program: E:\berlin-eventscout\3_evaluate_wb.py
                python: CPython 3.10.11
                root: E:\berlin-eventscout
                startedAt: "2026-06-26T13:52:16.350453Z"
                writerId: 8tg16heq1kwq21lcgjuuw75w7wlpy7zl
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
            "3":
                - 2
                - 13
            "4": 3.10.11
            "5": 0.27.0
            "6": 5.12.1
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
